export const birthdayWishes = [
  { text: 'I love you ❤️', size: 56 },
  { text: 'You are my universe', size: 48 },
  { text: 'Thank you for being my sunshine', size: 44 },
  { text: 'Thank you for being my sunshine', size: 44 },
  { text: 'Honey bunch, you are my everything', size: 46 },
  { text: 'Honey bunch, you are my everything', size: 46 },
  { text: 'I love you so much!', size: 50 },
  { text: 'Thank you for being my everything', size: 42 },
  { text: 'Thank you for being my everything', size: 42 },
  { text: 'You are my everything!', size: 46 },
  { text: 'You are my everything!', size: 46 },
  { text: 'Thank you for being in my life', size: 40 },
  { text: 'Thank you for being in my life', size: 40 },
  { text: 'I love you more each day', size: 44 },
  { text: 'I love you more each day', size: 44 },
  { text: 'Forever and always', size: 48 },
  { text: 'My heart belongs to you', size: 42 },
  { text: 'Together forever 💕', size: 46 },
  { text: '05/12/2002 💖', size: 52 },
  { text: '05/12/2002 🎂', size: 52 },
  { text: '05/12/2002 💖', size: 52 },
  { text: '05/12/2002 💖', size: 52 },
  { text: '05/12/2002 💖', size: 52 },
  { text: 'My love 05/12/2002', size: 52 },
  { text: 'My love for you is endless', size: 42 },
  { text: 'You light up my world', size: 48 },
  { text: 'Forever yours', size: 50 },
  { text: 'You mean everything to me', size: 44 },
  { text: 'Happy Birthday my love! 🎂', size: 54 },
  { text: 'Always and forever 💝', size: 46 },
  { text: 'You\'re my soulmate', size: 48 },
  { text: 'Thank you for everything', size: 42 },
  { text: 'Thank you for everything', size: 42 },
  { text: 'You\'re my favorite person', size: 48 },
  { text: 'You\'re my favorite person', size: 48 },
  { text: 'My heart is yours', size: 44 },
  { text: 'I love your smile', size: 42 },
  { text: 'You make me so happy', size: 46 },
  { text: 'Thanh Thuý 🎂 05/12/2002 💝', size: 46 },
  { text: 'Thanh Thuý 🎂 05/12/2002 💝', size: 46 },
  { text: 'Thanh Thuý 🎂 05/12/2002 💝', size: 46 },

  { text: 'I love you ❤️', size: 56 },
  { text: 'You are my universe', size: 48 },
  { text: 'Thank you for being my sunshine', size: 44 },
  { text: 'Thank you for being my sunshine', size: 44 },
  { text: 'Honey bunch, you are my everything', size: 46 },
  { text: 'Honey bunch, you are my everything', size: 46 },
];

export const photos = [
  '/images/emiu-1.png',
  // '/images/emiu-2.png',
  '/images/emiu-3.png',
  // '/images/emiu-4.png',
  // '/images/emiu-5.png',
  // '/images/emiu-6.png',
  // '/images/emiu-7.png',
  // '/images/emiu-8.png',
  // '/images/emiu-9.png',
  '/images/emiu-10.png',
  '/images/emiu-11.png',
  // '/images/emiu-12.png',
  // '/images/emiu-13.png',
  '/images/emiu-14.png',
  // '/images/emiu-15.png',
  // '/images/emiu-16.png',
  '/images/emiu-17.png',
  // '/images/emiu-18.png',
  // '/images/emiu-19.png',
  '/images/emiu-20.png',
  '/images/emiu-21.png',
  // '/images/emiu-22.png',
  '/images/emiu-23.png',
  '/images/emiu-24.png',
  '/images/emiu-25.png',
  // '/images/emiu-26.png',
  // '/images/emiu-27.png',
  // '/images/emiu-28.png',
  // '/images/emiu-29.png',
  // '/images/emiu-30.png',  
  '/images/emiu-32.png',
  // '/images/emiu-33.png',
  // '/images/emiu-34.png',
  // '/images/emiu-35.png',
];

